## Scipy linear algebra-Scipy Linalg

The SciPy package includes the features of the NumPy package in Python. It uses NumPy arrays as the fundamental data structure. It has all the features included in the linear algebra of the NumPy module and some extended functionality. It consists of a linalg submodule, and there is an overlap in the functionality provided by the SciPy and NumPy submodules.

## SOLVING LINEAR EGUATIONS

The **linalg.solve** function is used to solve the given linear equations. It is used to evaluate the equations automatically and find the values of the unknown variables.<br>
Suppose the linear equations are:

7x + 2y = 8
4x +5y =10


In [2]:
from scipy import linalg
import numpy as np

#Thw function takes two arrays
a=np.array([[7,2],[4,5]])
b=np.array([8,10])

#solving the linear equation
result=linalg.solve(a,b)
result

array([0.74074074, 1.40740741])

## Calculating the inverse of a matrix

The **scipy.linalg.inv** is used  to find the inverse of a matrix


consider:
A=[7  2
   4,5]

In [3]:
#Initializing the matrix
x=np.array([[7,2],[4,5]])

#Finding the inverse of x
y=linalg.inv(x)
y

array([[ 0.18518519, -0.07407407],
       [-0.14814815,  0.25925926]])

## Calculating the Pseudo Inverse of a Matrix <br>
To evaluate the (Moore-Penrose) pseudo-inverse of a matrix,   **scipy.linalg.pinv** is used.



In [4]:
x=np.array([[8,2],[3,5],[1,3]])

y=linalg.pinv(x)
y

array([[ 0.14251208, -0.03381643, -0.03864734],
       [-0.07487923,  0.16183575,  0.11352657]])

## Finding the determinant of a matrix

The determinant of a square matrix is a value derived arithmetically from the coefficients of the matrix. In the linalg module, we use the **linalg.det()** function to find the determinant of a matrix.


In [5]:
A=np.array([[9,6],[4,5]])

#finding the det
D=linalg.det(A)
D

21.0

## Singular Value Decomposition 

The Singular-Value Decomposition is a matrix decomposition method for reducing a matrix to its constituent parts to make specific subsequent matrix calculations simpler. It is calculated using **scipy.linalg.svd**.


In [6]:
M=np.array([[1,5],[6,10]])

#passing the values to the eigen fxn
x,y,z=linalg.svd(M)
print(x,y,z)

[[-0.38684104 -0.92214641]
 [-0.92214641  0.38684104]] [12.62901571  1.58365469] [[-0.46873958 -0.88333641]
 [ 0.88333641 -0.46873958]]


## Eigenvalues and EigenVectors

Let M be an n×n matrix and let X∈Cn be a non-zero vector for which:

MX = λX for some scalar λ.
λ is called an eigenvalue of the matrix M and X is called an eigenvector of M associated with λ, or a λ-eigenvector of M

The function scipy.linalg.eig takes a complex or a real matrix M whose eigenvalues and eigenvectors are to be evaluated. It returns the scalar set of eigenvalues for the matrix. It finds the eigenvalues and the right or left eigenvectors of the matrix.

In [8]:
M=np.array([[9,3],[2,4]])

val,vect = linalg.eig(M)

print(val)
print(vect)

[10.+0.j  3.+0.j]
[[ 0.9486833  -0.4472136 ]
 [ 0.31622777  0.89442719]]


## Calculating the norm

To define how close two vectors or matrices are, and to define the convergence of sequences of vectors or matrices, the norm is used. The function scipy.linalg.norm is used to calculate the matrix or vector norm.

The function scipy.linalg.norm returns one of the seven different matrix norms or one of an infinite number of vector norms. 

    -The L2 norm evaluates the distance of the vector coordinate from the origin of the vector space. It is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. The result is a positive distance value.<br>
    -The L1 norm is evaluated as the sum of the absolute vector values. It is an evaluation of the Manhattan distance from the origin of the vector space.


In [10]:
#initializing the input array
x=np.array([6,3])

#calculating the L2 norm
a=linalg.norm(x)

#calcullating the L1 norm
b=linalg.norm(x,1)

print(a)
print(b)

6.708203932499369
9.0


## More Matrix Functions

Function Name	              Definition

scipy.linalg.sqrtm(A, disp, blocksize)	Finds the square root of the matrix.

scipy.linalg.expm(A)	Computes the matrix exponential using Pade approximation.

scipy.linalg.sinm(A)	Computes the sine of the matrix.

scipy.linalg.cosm(A)	Computes the cosine of the matrix.

scipy.linalg.tanm(A)	Computes the tangent of the matrix.