**Basics of Numpy Arrays**

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used.<br>
We'll cover a few categories of basic array manipulations here:

-**Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays<br>
-**Indexing of arrays**: Getting and setting the value of individual array elements<br>
-**Slicing of arrays**: Getting and setting smaller subarrays within a larger array<br>
-**Reshaping of arrays**: Changing the shape of a given array<br>
-**Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many<br>

#NumPy Array Attributes
First let's discuss some useful array attributes. We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array. We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [1]:
import numpy as np
np.random.seed(0) #seed for reproducibility
x1=np.random.randint(10,size=6) #1D array
x2=np.random.randint(10,size=(3,4)) #2D array
x3=np.random.randint(10,size=(3,4,5)) #3D array


In [4]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [3]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [2]:
print("x3 ndim: ",x3.ndim)
print("x3 shape: ",x3.shape)
print("x3 size: ",x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [5]:
#we can also check the dtype of the array
print("dtype:", x3.dtype)

dtype: int32


#Array Indexing: Accessing Single Elements<br>
In a one-dimensional array, the ith
value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists.


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[4]

7

To index from the end of the array,you can use negative indices:

In [8]:
x1[-1]

9

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [9]:
x2[0,0]

3

In [10]:
x2[2,0]

1

In [11]:
x2[2,-1]

7

Values can also be modified using any of the above index notation

In [12]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [13]:
x1[0]=3.141359  #this will be truncated
x1

array([3, 0, 3, 3, 7, 9])

#Array slicing: Accessing subarrays<br>
Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array X use;

x[start:stop:step]

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

## One-dimensional subarrays

In [4]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[:5] #first 5 elements

array([0, 1, 2, 3, 4])

In [6]:
x[4:7] #midde sub-array

array([4, 5, 6])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [8]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
x[5::-2] #reversed every other from i

array([5, 3, 1])

## Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas. For example:

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[:2, :3] #two rows, 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [12]:
x2[:3, ::2]  #all rows,every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

Subarray dimensions can even be reversed together

In [13]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

## Accessing array rows and columns <br>
One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [14]:
x2[:,0] #first column

array([3, 7, 1])

In [15]:
x2[0,:] #first column

array([3, 5, 2, 4])

## Subarrays as no-copy views <br>
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Lets extract 2 X 2 subarray from this

In [17]:
x2_sub=x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

Now if we modify this subarray,we'll see that the original array is changed

In [18]:
x2_sub[0, 0]=99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [19]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

## Creating copies of arrays <br>
This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.



In [20]:
x2_sub_copy=x2[:2, :2].copy()
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

If we modify this subaarray, the original is untouched

In [21]:
x2_sub_copy[0, 0]=42
x2_sub_copy

array([[42,  5],
       [ 7,  6]])

In [22]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## REshaping of arrays <br>
Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3
 grid, you can do the following:



In [23]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [24]:
x=np.array([1,2,3])
#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [25]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [26]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

## Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

## Spliting of arrays

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:
